version: '0.1.0-build{build}'
configuration:
- Release
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
test_script:
- dotnet test "sln\Amongst.Test\Amongst.Test.csproj" --no-build -c %CONFIGURATION%
artifacts:
- path: sln\Amongst\bin\%CONFIGURATION%\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'