version: '0.1.0-build{build}'
configuration:
- Release
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "sln\Amongst\Amongst.csproj" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL% -o artifacts\Mongest
#test_script:
#- dotnet test "sln\Amongst.Test\Amongst.Test.csproj" -c %CONFIGURATION%
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'